2022-08-17 18:50:14,258 INFO    Thread-2  :121981 [wandb_setup.py:_flush():75] Loading settings from /home/mgatlin3/.config/wandb/settings
2022-08-17 18:50:14,258 INFO    Thread-2  :121981 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-08-17 18:50:14,258 INFO    Thread-2  :121981 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'sweep-FT', 'entity': 'mgatlin3', 'root_dir': '/home/mgatlin3/FT', 'sweep_id': '3epcegps', 'run_id': 'alvyhhhn', 'sweep_param_path': '/home/mgatlin3/FT/wandb/sweep-3epcegps/config-alvyhhhn.yaml'}
2022-08-17 18:50:14,258 INFO    Thread-2  :121981 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'sweep.py', 'program': '/home/mgatlin3/FT/sweep.py'}
2022-08-17 18:50:14,258 INFO    Thread-2  :121981 [wandb_init.py:_log_setup():437] Logging user logs to /home/mgatlin3/FT/wandb/run-20220817_185014-alvyhhhn/logs/debug.log
2022-08-17 18:50:14,259 INFO    Thread-2  :121981 [wandb_init.py:_log_setup():438] Logging internal logs to /home/mgatlin3/FT/wandb/run-20220817_185014-alvyhhhn/logs/debug-internal.log
2022-08-17 18:50:14,259 INFO    Thread-2  :121981 [wandb_init.py:init():471] calling init triggers
2022-08-17 18:50:14,259 INFO    Thread-2  :121981 [wandb_init.py:init():474] wandb.init called with sweep_config: {'batch_size': 32, 'dropout_c': 0.3, 'dropout_ga': 0.25, 'epoch': 50, 'learning_rate': 0.00075, 'num_features_c1': 64, 'num_features_c2': 32, 'num_features_c3': 16, 'num_features_c4': 128}
config: {'batch_size': 4, 'epochs': 5, 'dropout_c': 0.3, 'dropout_ga': 0.1, 'num_features_c1': 64, 'num_features_c2': 64, 'num_features_c3': 128, 'num_features_c4': 64, 'learning_rate': 0.0003}
2022-08-17 18:50:14,259 INFO    Thread-2  :121981 [wandb_init.py:init():524] starting backend
2022-08-17 18:50:14,259 INFO    Thread-2  :121981 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-17 18:50:14,272 INFO    Thread-2  :121981 [backend.py:ensure_launched():217] starting backend process...
2022-08-17 18:50:14,278 INFO    Thread-2  :121981 [backend.py:ensure_launched():222] started backend process with pid: 122006
2022-08-17 18:50:14,279 INFO    Thread-2  :121981 [wandb_init.py:init():533] backend started and connected
2022-08-17 18:50:14,286 INFO    Thread-2  :121981 [wandb_run.py:_config_callback():1131] config_cb None None {'batch_size': 32, 'dropout_c': 0.3, 'dropout_ga': 0.25, 'epoch': 50, 'learning_rate': 0.00075, 'num_features_c1': 64, 'num_features_c2': 32, 'num_features_c3': 16, 'num_features_c4': 128}
2022-08-17 18:50:14,288 INFO    Thread-2  :121981 [wandb_init.py:init():597] updated telemetry
2022-08-17 18:50:14,302 INFO    Thread-2  :121981 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-08-17 18:50:14,988 INFO    Thread-2  :121981 [wandb_run.py:_on_init():1923] communicating current version
2022-08-17 18:50:15,082 INFO    Thread-2  :121981 [wandb_run.py:_on_init():1927] got version response upgrade_message: "wandb version 0.13.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-08-17 18:50:15,082 INFO    Thread-2  :121981 [wandb_init.py:init():659] starting run threads in backend
2022-08-17 18:50:19,440 INFO    Thread-2  :121981 [wandb_run.py:_console_start():1897] atexit reg
2022-08-17 18:50:19,441 INFO    Thread-2  :121981 [wandb_run.py:_redirect():1770] redirect: SettingsConsole.REDIRECT
2022-08-17 18:50:19,442 INFO    Thread-2  :121981 [wandb_run.py:_redirect():1775] Redirecting console.
2022-08-17 18:50:19,442 ERROR   Thread-2  :121981 [wandb_run.py:_redirect():1834] Failed to redirect.
Traceback (most recent call last):
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1827, in _redirect
    out_redir.install()
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/home/mgatlin3/.local/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/mgatlin3/.conda/envs/poop/lib/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-08-17 18:50:19,444 INFO    Thread-2  :121981 [wandb_init.py:init():684] run started, returning control to user process
2022-08-17 18:50:19,445 INFO    Thread-2  :121981 [wandb_config.py:__setitem__():150] config set architecture_name = CNN - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7ff3440cd700>>
2022-08-17 18:50:19,445 INFO    Thread-2  :121981 [wandb_run.py:_config_callback():1131] config_cb architecture_name CNN None
2022-08-17 18:50:19,695 INFO    Thread-2  :121981 [wandb_run.py:_finish():1685] finishing run mgatlin3/sweep-FT/alvyhhhn
2022-08-17 18:50:19,695 INFO    Thread-2  :121981 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 1
2022-08-17 18:50:19,697 INFO    Thread-2  :121981 [wandb_run.py:_restore():1838] restore
2022-08-17 18:50:19,700 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 777
  total_bytes: 777
}

2022-08-17 18:50:19,878 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 777
  total_bytes: 777
}

2022-08-17 18:50:20,014 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 777
  total_bytes: 10170
}

2022-08-17 18:50:20,116 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7321
  total_bytes: 10170
}

2022-08-17 18:50:20,217 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10170
  total_bytes: 10170
}

2022-08-17 18:50:20,319 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10170
  total_bytes: 10170
}

2022-08-17 18:50:20,421 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10170
  total_bytes: 10170
}

2022-08-17 18:50:20,522 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10170
  total_bytes: 10170
}

2022-08-17 18:50:20,624 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10170
  total_bytes: 10170
}

2022-08-17 18:50:20,808 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10170
  total_bytes: 10170
}

2022-08-17 18:50:21,021 INFO    Thread-2  :121981 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 10170
  total_bytes: 10170
}
local_info {
}

2022-08-17 18:50:22,460 INFO    Thread-2  :121981 [wandb_run.py:_footer_history_summary_info():3102] rendering history
2022-08-17 18:50:22,460 INFO    Thread-2  :121981 [wandb_run.py:_footer_history_summary_info():3134] rendering summary
2022-08-17 18:50:22,461 INFO    Thread-2  :121981 [wandb_run.py:_footer_sync_info():3057] logging synced files
